"""Schema creation and migrations.

Schema versions
---------------
v1 — initial schema (experiments, triples, model_checkpoints, paper_log,
     metrics_history, agent_events).
v2 — adds `tool_versions` table + nullable `tool_version_id` columns on
     `triples` and `model_checkpoints`. This supports the co-evolution model
     described in docs/PLANCKBOT_CONCEPT.md §7: every tool call is tagged
     with the hash of the tool source it ran against, so adapters never get
     applied to a tool they weren't trained on.
v3 — adds `cron_jobs` table for the background job scheduler (auto-label,
     retrain, …). Purely additive.
v4 — adds Layer D tables:
     `synthesized_tools` (tools generated by observing usage patterns,
     exposed through the `planckbot-synth` MCP server), and
     `gap_reports` (outputs of the pattern detector — "sequence X→Y→Z
     repeats often enough to justify a merged tool").
v5 — adds `blessed` (bool) and `tuned_threshold` (float) columns to
     `model_checkpoints`. A checkpoint must be `blessed=1` before the
     proxy will apply it in `intervene` mode, and its tuned threshold
     (if set) overrides the global default. Both are additive nullable
     columns.
v6 — adds `projects` table + nullable `project_id` columns on
     `triples`, `model_checkpoints`, `cron_jobs`, `synthesized_tools`,
     `gap_reports`, and `experiments`. Lets the user define multiple
     target folders ("projects"), scope data and adapters per-project,
     and switch which one Claude Code points at without losing history
     from the others. Existing rows get NULL `project_id` (treated as
     "legacy / unscoped" — visible in All-Projects views, invisible in
     any per-project filter) so the upgrade is lossless.
v7 — adds `activity_events` table for the cross-process live-activity
     feed. Proxy, cron daemon, synth, and training all INSERT rows
     when they do something notable; the UI's /activity page polls
     this table as a SQLite-backed event bus. Rotation is app-side
     (src/planckbot/activity.py :: trim_events).
v8 — adds `tool_cache` table for the PreToolUse cache-deny path (Layer A
     technique from the 2026-05-21 Tier-1 bench). Stores recent tool
     outputs keyed by (session_id, tool_name, cache_key) so a PreToolUse
     hook can short-circuit repeat Reads / idempotent Bash with the
     cached content as the denial reason. mtime + dirty flag prevent
     stale-cache returns when the underlying file was edited.
"""

import sqlite3

SCHEMA_VERSION = 8

TABLES = """
CREATE TABLE IF NOT EXISTS schema_version (
    version INTEGER NOT NULL
);

-- v6: projects = named target folders. The user creates one per repo/codebase
-- they want PlanckBot to watch. At any time exactly zero or one project has
-- `is_active = 1`; its `path` is the one baked into the planckbot-fs MCP
-- entry in ~/.claude.json. Rows in the per-project tables (triples,
-- checkpoints, cron_jobs, synthesized_tools, gap_reports, experiments)
-- carry a `project_id` so we can segregate training data and adapters by
-- project. NULL `project_id` = legacy unscoped data from before v6.
CREATE TABLE IF NOT EXISTS projects (
    id           TEXT PRIMARY KEY,
    name         TEXT NOT NULL UNIQUE,
    path         TEXT NOT NULL,
    description  TEXT,
    is_active    INTEGER NOT NULL DEFAULT 0,
    created_at   TEXT NOT NULL,
    last_used_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_projects_active ON projects(is_active);

CREATE TABLE IF NOT EXISTS experiments (
    id              TEXT PRIMARY KEY,
    name            TEXT NOT NULL,
    description     TEXT,
    hypothesis      TEXT,
    experiment_type TEXT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'planned',
    config          TEXT NOT NULL DEFAULT '{}',
    random_seed     INTEGER,
    data_snapshot   TEXT,
    checkpoint_id   TEXT,
    created_at      TEXT NOT NULL,
    started_at      TEXT,
    completed_at    TEXT,
    metrics         TEXT,
    observations    TEXT,
    project_id      TEXT,                 -- v6: target project
    FOREIGN KEY (checkpoint_id) REFERENCES model_checkpoints(id),
    FOREIGN KEY (project_id) REFERENCES projects(id)
);

CREATE TABLE IF NOT EXISTS triples (
    id              TEXT PRIMARY KEY,
    tool_name       TEXT NOT NULL,
    session_id      TEXT,
    input_data      TEXT NOT NULL,
    context_data    TEXT,
    output_data     TEXT NOT NULL,
    input_tokens    INTEGER,
    output_tokens   INTEGER,
    filtered_output TEXT,
    filtered_tokens INTEGER,
    source          TEXT DEFAULT 'manual',
    created_at      TEXT NOT NULL,
    experiment_id   TEXT,
    tool_version_id TEXT,                 -- v2: which tool revision this was observed on
    project_id      TEXT,                 -- v6: which project this triple belongs to
    FOREIGN KEY (experiment_id) REFERENCES experiments(id),
    FOREIGN KEY (tool_version_id) REFERENCES tool_versions(id),
    FOREIGN KEY (project_id) REFERENCES projects(id)
);

CREATE INDEX IF NOT EXISTS idx_triples_tool ON triples(tool_name);
CREATE INDEX IF NOT EXISTS idx_triples_experiment ON triples(experiment_id);
CREATE INDEX IF NOT EXISTS idx_triples_project ON triples(project_id);

-- v2: tool_versions + tool_version_id columns.
-- See docs/PLANCKBOT_CONCEPT.md §7 (Mutable Tools & Co-evolution).
--
-- Every callable PlanckBot observes is content-hashed. A new hash = a new
-- version row. Triples and checkpoints carry the version they were
-- recorded/trained against so an adapter never gets applied to a tool
-- revision it wasn't trained on.
CREATE TABLE IF NOT EXISTS tool_versions (
    id                TEXT PRIMARY KEY,
    tool_name         TEXT NOT NULL,
    code_hash         TEXT NOT NULL,      -- sha256 of the tool source
    source            TEXT,               -- optional: the actual code
    created_at        TEXT NOT NULL,
    created_by        TEXT,               -- 'human' | 'prompt:<id>' | 'agent:<name>'
    parent_version_id TEXT,
    diff_from_parent  TEXT,               -- unified diff, for audit + rollback
    FOREIGN KEY (parent_version_id) REFERENCES tool_versions(id)
);

CREATE INDEX IF NOT EXISTS idx_tool_versions_name ON tool_versions(tool_name);
CREATE UNIQUE INDEX IF NOT EXISTS idx_tool_versions_hash
    ON tool_versions(tool_name, code_hash);

CREATE TABLE IF NOT EXISTS model_checkpoints (
    id              TEXT PRIMARY KEY,
    name            TEXT NOT NULL,
    base_model      TEXT NOT NULL,
    model_size_mb   REAL,
    adapter_path    TEXT,
    adapter_size_mb REAL,
    experiment_id   TEXT,
    strategy        TEXT,
    tool_name       TEXT,
    tool_version_id TEXT,                 -- v2: which tool revision this was trained on
    lora_config     TEXT,
    training_args   TEXT,
    num_triples     INTEGER,
    eval_metrics    TEXT,
    is_active       INTEGER DEFAULT 0,
    blessed         INTEGER NOT NULL DEFAULT 0,        -- v5: safety gate
    tuned_threshold REAL,                              -- v5: per-ckpt θ
    created_at      TEXT NOT NULL,
    project_id      TEXT,                 -- v6: which project this adapter is for
    FOREIGN KEY (experiment_id) REFERENCES experiments(id),
    FOREIGN KEY (tool_version_id) REFERENCES tool_versions(id),
    FOREIGN KEY (project_id) REFERENCES projects(id)
);

CREATE INDEX IF NOT EXISTS idx_checkpoints_tool_version
    ON model_checkpoints(tool_name, tool_version_id);
CREATE INDEX IF NOT EXISTS idx_checkpoints_project
    ON model_checkpoints(project_id, tool_name);

CREATE TABLE IF NOT EXISTS paper_log (
    id              TEXT PRIMARY KEY,
    experiment_id   TEXT,
    entry_type      TEXT NOT NULL,
    title           TEXT NOT NULL,
    content         TEXT NOT NULL,
    tags            TEXT,
    created_at      TEXT NOT NULL,
    updated_at      TEXT,
    FOREIGN KEY (experiment_id) REFERENCES experiments(id)
);

CREATE TABLE IF NOT EXISTS metrics_history (
    id              TEXT PRIMARY KEY,
    experiment_id   TEXT NOT NULL,
    recorded_at     TEXT NOT NULL,
    metric_name     TEXT NOT NULL,
    metric_value    REAL NOT NULL,
    step            INTEGER,
    metadata        TEXT
);

CREATE INDEX IF NOT EXISTS idx_metrics_experiment ON metrics_history(experiment_id, metric_name);

CREATE TABLE IF NOT EXISTS agent_events (
    id              TEXT PRIMARY KEY,
    tool_name       TEXT NOT NULL,
    event_type      TEXT NOT NULL,
    timestamp       TEXT NOT NULL,
    details         TEXT,
    session_id      TEXT
);

CREATE INDEX IF NOT EXISTS idx_agent_events_tool ON agent_events(tool_name);
CREATE INDEX IF NOT EXISTS idx_agent_events_time ON agent_events(timestamp);

-- v3: scheduled jobs (auto-label, retrain, …).
CREATE TABLE IF NOT EXISTS cron_jobs (
    id               TEXT PRIMARY KEY,
    name             TEXT NOT NULL UNIQUE,
    job_type         TEXT NOT NULL,          -- 'autolabel' | 'retrain' | 'noop'
    params           TEXT NOT NULL DEFAULT '{}',
    interval_seconds INTEGER NOT NULL,
    enabled          INTEGER NOT NULL DEFAULT 1,
    last_run_at      TEXT,
    next_run_at      TEXT,
    last_status      TEXT,                   -- 'ok' | 'error' | NULL
    last_output      TEXT,
    created_at       TEXT NOT NULL,
    project_id       TEXT,                   -- v6: which project this job is for (NULL = global)
    FOREIGN KEY (project_id) REFERENCES projects(id)
);

CREATE INDEX IF NOT EXISTS idx_cron_due ON cron_jobs(enabled, next_run_at);
CREATE INDEX IF NOT EXISTS idx_cron_project ON cron_jobs(project_id);

-- v4: Layer D — synthesized tools + gap reports.
CREATE TABLE IF NOT EXISTS synthesized_tools (
    id                TEXT PRIMARY KEY,
    name              TEXT NOT NULL UNIQUE,
    description       TEXT NOT NULL DEFAULT '',
    input_schema      TEXT NOT NULL DEFAULT '{}',
    code              TEXT NOT NULL,
    source_file_path  TEXT,
    status            TEXT NOT NULL DEFAULT 'draft',  -- draft | active | retired
    created_at        TEXT NOT NULL,
    created_by        TEXT,
    gap_report_id     TEXT,
    project_id        TEXT,                 -- v6: which project this tool was synthesized from
    FOREIGN KEY (gap_report_id) REFERENCES gap_reports(id),
    FOREIGN KEY (project_id) REFERENCES projects(id)
);

CREATE INDEX IF NOT EXISTS idx_synth_status ON synthesized_tools(status);
CREATE INDEX IF NOT EXISTS idx_synth_project ON synthesized_tools(project_id);

CREATE TABLE IF NOT EXISTS gap_reports (
    id                      TEXT PRIMARY KEY,
    tool_sequence           TEXT NOT NULL,           -- JSON list of tool names
    occurrences             INTEGER NOT NULL,
    example_triple_ids      TEXT NOT NULL,           -- JSON list of ids
    proposed_name           TEXT,
    proposed_description    TEXT,
    status                  TEXT NOT NULL DEFAULT 'open', -- open | accepted | rejected
    created_at              TEXT NOT NULL,
    project_id              TEXT,                    -- v6: which project this gap was detected in
    FOREIGN KEY (project_id) REFERENCES projects(id)
);

CREATE INDEX IF NOT EXISTS idx_gap_status ON gap_reports(status);
CREATE INDEX IF NOT EXISTS idx_gap_project ON gap_reports(project_id);

-- v7: cross-process event bus for the /activity live-log page.
-- Proxy, cron daemon, synth, and training all INSERT rows when they do
-- something notable; the UI polls `id > last_seen` every few seconds.
CREATE TABLE IF NOT EXISTS activity_events (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    ts           TEXT NOT NULL,
    source       TEXT NOT NULL,      -- proxy | cron | synth | training | ui
    kind         TEXT NOT NULL,      -- rx, upstream, redact, store, job_start, …
    message      TEXT NOT NULL,
    meta         TEXT,               -- optional JSON blob
    project_id   TEXT
);

CREATE INDEX IF NOT EXISTS idx_activity_ts ON activity_events(ts DESC);
CREATE INDEX IF NOT EXISTS idx_activity_id ON activity_events(id);

-- v8: tool_cache = per-session memoization for the PreToolUse cache-deny
-- path. The hook looks up by (session_id, tool_name, cache_key). For Read,
-- cache_key is the absolute file_path and `file_mtime_ns` lets us spot
-- staleness (the hook compares against disk on lookup). `dirty` is set
-- when a later Edit/Write hits the same path in the same session, so we
-- never serve a stale cache to the LLM. `hits` counts how often this
-- entry served a request — useful for telemetry + ablation.
CREATE TABLE IF NOT EXISTS tool_cache (
    id              TEXT PRIMARY KEY,
    session_id      TEXT NOT NULL,
    project_id      TEXT,
    tool_name       TEXT NOT NULL,
    cache_key       TEXT NOT NULL,
    file_path       TEXT,
    file_mtime_ns   INTEGER,
    content         TEXT NOT NULL,
    content_tokens  INTEGER,
    dirty           INTEGER NOT NULL DEFAULT 0,
    hits            INTEGER NOT NULL DEFAULT 0,
    created_at      TEXT NOT NULL,
    last_hit_at     TEXT,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_tool_cache_lookup
    ON tool_cache(session_id, tool_name, cache_key);
CREATE INDEX IF NOT EXISTS idx_tool_cache_path
    ON tool_cache(session_id, file_path);
CREATE INDEX IF NOT EXISTS idx_tool_cache_created
    ON tool_cache(created_at DESC);
"""


V2_UPGRADE_STATEMENTS = [
    # Table creation is idempotent via IF NOT EXISTS.
    """
    CREATE TABLE IF NOT EXISTS tool_versions (
        id                TEXT PRIMARY KEY,
        tool_name         TEXT NOT NULL,
        code_hash         TEXT NOT NULL,
        source            TEXT,
        created_at        TEXT NOT NULL,
        created_by        TEXT,
        parent_version_id TEXT,
        diff_from_parent  TEXT,
        FOREIGN KEY (parent_version_id) REFERENCES tool_versions(id)
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_tool_versions_name ON tool_versions(tool_name)",
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_tool_versions_hash ON tool_versions(tool_name, code_hash)",
    # Column adds on existing tables — guarded below since SQLite has no
    # "IF NOT EXISTS" form for ALTER TABLE ADD COLUMN.
]


def _column_exists(conn: sqlite3.Connection, table: str, column: str) -> bool:
    cur = conn.execute(f"PRAGMA table_info({table})")
    return any(row[1] == column for row in cur.fetchall())


def _get_current_version(conn: sqlite3.Connection) -> int:
    row = conn.execute("SELECT MAX(version) FROM schema_version").fetchone()
    return int(row[0]) if row and row[0] is not None else 0


def _upgrade_to_v2(conn: sqlite3.Connection) -> None:
    """Add v2 artifacts to an existing v1 database.

    v2 adds `tool_versions` table + nullable `tool_version_id` columns on
    `triples` and `model_checkpoints`. All additions are backward-compatible —
    existing rows keep working; `tool_version_id` is NULL until the proxy
    starts tagging new calls with a version.
    """
    for stmt in V2_UPGRADE_STATEMENTS:
        conn.execute(stmt)
    if not _column_exists(conn, "triples", "tool_version_id"):
        conn.execute("ALTER TABLE triples ADD COLUMN tool_version_id TEXT")
    if not _column_exists(conn, "model_checkpoints", "tool_version_id"):
        conn.execute(
            "ALTER TABLE model_checkpoints ADD COLUMN tool_version_id TEXT"
        )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_checkpoints_tool_version "
        "ON model_checkpoints(tool_name, tool_version_id)"
    )


V3_UPGRADE_STATEMENTS = [
    """
    CREATE TABLE IF NOT EXISTS cron_jobs (
        id               TEXT PRIMARY KEY,
        name             TEXT NOT NULL UNIQUE,
        job_type         TEXT NOT NULL,
        params           TEXT NOT NULL DEFAULT '{}',
        interval_seconds INTEGER NOT NULL,
        enabled          INTEGER NOT NULL DEFAULT 1,
        last_run_at      TEXT,
        next_run_at      TEXT,
        last_status      TEXT,
        last_output      TEXT,
        created_at       TEXT NOT NULL
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_cron_due ON cron_jobs(enabled, next_run_at)",
]


def _upgrade_to_v3(conn: sqlite3.Connection) -> None:
    """Add v3 artifacts to an existing v2 database."""
    for stmt in V3_UPGRADE_STATEMENTS:
        conn.execute(stmt)


V4_UPGRADE_STATEMENTS = [
    """
    CREATE TABLE IF NOT EXISTS gap_reports (
        id                      TEXT PRIMARY KEY,
        tool_sequence           TEXT NOT NULL,
        occurrences             INTEGER NOT NULL,
        example_triple_ids      TEXT NOT NULL,
        proposed_name           TEXT,
        proposed_description    TEXT,
        status                  TEXT NOT NULL DEFAULT 'open',
        created_at              TEXT NOT NULL
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_gap_status ON gap_reports(status)",
    """
    CREATE TABLE IF NOT EXISTS synthesized_tools (
        id                TEXT PRIMARY KEY,
        name              TEXT NOT NULL UNIQUE,
        description       TEXT NOT NULL DEFAULT '',
        input_schema      TEXT NOT NULL DEFAULT '{}',
        code              TEXT NOT NULL,
        source_file_path  TEXT,
        status            TEXT NOT NULL DEFAULT 'draft',
        created_at        TEXT NOT NULL,
        created_by        TEXT,
        gap_report_id     TEXT,
        FOREIGN KEY (gap_report_id) REFERENCES gap_reports(id)
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_synth_status ON synthesized_tools(status)",
]


def _upgrade_to_v4(conn: sqlite3.Connection) -> None:
    """Add v4 Layer D artifacts to an existing v3 database."""
    for stmt in V4_UPGRADE_STATEMENTS:
        conn.execute(stmt)


def _upgrade_to_v5(conn: sqlite3.Connection) -> None:
    """Add safety + calibration columns to model_checkpoints.

    Additive only. Existing rows get blessed=0 (safe default — they must
    be explicitly blessed before use) and tuned_threshold=NULL (falls back
    to the proxy's default).
    """
    if not _column_exists(conn, "model_checkpoints", "blessed"):
        conn.execute(
            "ALTER TABLE model_checkpoints "
            "ADD COLUMN blessed INTEGER NOT NULL DEFAULT 0"
        )
    if not _column_exists(conn, "model_checkpoints", "tuned_threshold"):
        conn.execute(
            "ALTER TABLE model_checkpoints "
            "ADD COLUMN tuned_threshold REAL"
        )


V6_UPGRADE_STATEMENTS = [
    """
    CREATE TABLE IF NOT EXISTS projects (
        id           TEXT PRIMARY KEY,
        name         TEXT NOT NULL UNIQUE,
        path         TEXT NOT NULL,
        description  TEXT,
        is_active    INTEGER NOT NULL DEFAULT 0,
        created_at   TEXT NOT NULL,
        last_used_at TEXT
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_projects_active ON projects(is_active)",
]


_V6_COLUMN_ADDS = [
    # (table, column, type)
    ("triples", "project_id", "TEXT"),
    ("model_checkpoints", "project_id", "TEXT"),
    ("cron_jobs", "project_id", "TEXT"),
    ("synthesized_tools", "project_id", "TEXT"),
    ("gap_reports", "project_id", "TEXT"),
    ("experiments", "project_id", "TEXT"),
]


_V6_INDEXES = [
    "CREATE INDEX IF NOT EXISTS idx_triples_project ON triples(project_id)",
    "CREATE INDEX IF NOT EXISTS idx_checkpoints_project "
    "ON model_checkpoints(project_id, tool_name)",
    "CREATE INDEX IF NOT EXISTS idx_cron_project ON cron_jobs(project_id)",
    "CREATE INDEX IF NOT EXISTS idx_synth_project "
    "ON synthesized_tools(project_id)",
    "CREATE INDEX IF NOT EXISTS idx_gap_project ON gap_reports(project_id)",
]


def _upgrade_to_v6(conn: sqlite3.Connection) -> None:
    """Add projects table + nullable project_id columns on the per-project
    tables.

    Intentionally lossless: existing rows get NULL project_id (treated as
    "legacy / unscoped" by the stores). The first `planckbot project create
    --adopt-legacy` can bulk-reassign them to a newly-created project.
    """
    for stmt in V6_UPGRADE_STATEMENTS:
        conn.execute(stmt)
    for table, column, coltype in _V6_COLUMN_ADDS:
        if not _column_exists(conn, table, column):
            conn.execute(
                f"ALTER TABLE {table} ADD COLUMN {column} {coltype}"
            )
    for stmt in _V6_INDEXES:
        conn.execute(stmt)


V8_UPGRADE_STATEMENTS = [
    """
    CREATE TABLE IF NOT EXISTS tool_cache (
        id              TEXT PRIMARY KEY,
        session_id      TEXT NOT NULL,
        project_id      TEXT,
        tool_name       TEXT NOT NULL,
        cache_key       TEXT NOT NULL,
        file_path       TEXT,
        file_mtime_ns   INTEGER,
        content         TEXT NOT NULL,
        content_tokens  INTEGER,
        dirty           INTEGER NOT NULL DEFAULT 0,
        hits            INTEGER NOT NULL DEFAULT 0,
        created_at      TEXT NOT NULL,
        last_hit_at     TEXT,
        FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_tool_cache_lookup ON tool_cache(session_id, tool_name, cache_key)",
    "CREATE INDEX IF NOT EXISTS idx_tool_cache_path ON tool_cache(session_id, file_path)",
    "CREATE INDEX IF NOT EXISTS idx_tool_cache_created ON tool_cache(created_at DESC)",
]


V7_UPGRADE_STATEMENTS = [
    """
    CREATE TABLE IF NOT EXISTS activity_events (
        id           INTEGER PRIMARY KEY AUTOINCREMENT,
        ts           TEXT NOT NULL,
        source       TEXT NOT NULL,      -- proxy | cron | synth | training | ui
        kind         TEXT NOT NULL,      -- rx, upstream, redact, store, job_start, …
        message      TEXT NOT NULL,
        meta         TEXT,               -- optional JSON blob
        project_id   TEXT                -- optional, for scoping in the UI
    )
    """,
    # Newest-first scans dominate the /activity page; index the timestamp
    # for cheap `ORDER BY ts DESC LIMIT N` and `WHERE id > ?` polling.
    "CREATE INDEX IF NOT EXISTS idx_activity_ts ON activity_events(ts DESC)",
    "CREATE INDEX IF NOT EXISTS idx_activity_id ON activity_events(id)",
]


def _upgrade_to_v7(conn: sqlite3.Connection) -> None:
    for stmt in V7_UPGRADE_STATEMENTS:
        conn.execute(stmt)


def _upgrade_to_v8(conn: sqlite3.Connection) -> None:
    for stmt in V8_UPGRADE_STATEMENTS:
        conn.execute(stmt)


def migrate(conn: sqlite3.Connection):
    """Apply pending migrations. Safe to call repeatedly."""
    cur = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name='schema_version'"
    )
    if cur.fetchone() is None:
        # Fresh DB — create everything at the latest version.
        conn.executescript(TABLES)
        conn.execute("INSERT INTO schema_version (version) VALUES (?)", (SCHEMA_VERSION,))
        conn.commit()
        return

    # Existing DB — apply incremental upgrades.
    current = _get_current_version(conn)
    if current >= SCHEMA_VERSION:
        return

    if current < 2:
        _upgrade_to_v2(conn)
    if current < 3:
        _upgrade_to_v3(conn)
    if current < 4:
        _upgrade_to_v4(conn)
    if current < 5:
        _upgrade_to_v5(conn)
    if current < 6:
        _upgrade_to_v6(conn)
    if current < 7:
        _upgrade_to_v7(conn)
    if current < 8:
        _upgrade_to_v8(conn)

    # Hygiene: store the version as a SINGLE row that we UPDATE in place.
    # Pre-v5 DBs have one row per migration (accumulating cruft); we
    # collapse them on migration.
    conn.execute("DELETE FROM schema_version")
    conn.execute("INSERT INTO schema_version (version) VALUES (?)", (SCHEMA_VERSION,))
    conn.commit()
